package GUI;
import Task3.View;
import Task4.ViewableTable;
import Task5.*;
import Task7.ConcreteObserver;
import Task7.Subject;
import java.io.IOException;
/** GUI головне меню
 * @author Яценко Віталій */
public class Menu extends javax.swing.JFrame {
    private View view = new ViewableTable().getView();
    ConcreteObserver concreteObserver = new ConcreteObserver(); Subject subject = new Subject();
    Graphic graph = new Graphic("Surviving Cells");
    /**
     * Creates new form Menu
     */
    public Menu() { initComponents(); graph.setVisible(false); subject.registerObserver(concreteObserver); }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangeButton = new javax.swing.JButton();
        GraphButton = new javax.swing.JButton();
        GenerateButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        RestoreButton = new javax.swing.JButton();
        ResultLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Surviving cells");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 500));
        setLocationByPlatform(true);

        ChangeButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ChangeButton.setText("Change");
        ChangeButton.setToolTipText("Change generated values");
        ChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeButtonActionPerformed(evt);
            }
        });

        GraphButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        GraphButton.setText("Draw graph");
        GraphButton.setToolTipText("Draw chart about cells");
        GraphButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        GraphButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphButtonActionPerformed(evt);
            }
        });

        GenerateButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        GenerateButton.setText("Generate");
        GenerateButton.setToolTipText("Generate values for graphic");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        SaveButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setToolTipText("Save data to file");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        RestoreButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        RestoreButton.setText("Restore");
        RestoreButton.setToolTipText("Restore data from file");
        RestoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreButtonActionPerformed(evt);
            }
        });

        ResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultLabel.setText("Choose action");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Cell viability simulation");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(GenerateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ChangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(RestoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(GraphButton)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 99, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(GraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** Кнопка для зміни значень */
    private void ChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeButtonActionPerformed
        ChangeConsoleCommand change = new ChangeConsoleCommand(view);
        change.execute();
        graph.updateGraph(view);
        ResultLabel.setText("Change complete");
        subject.notifyObservers(view);
    }//GEN-LAST:event_ChangeButtonActionPerformed

    /** Кнопка для відображення графіку */
    private void GraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphButtonActionPerformed
        graph.updateGraph(view);
        graph.setVisible(true);
        ResultLabel.setText("Graph generated");
    }//GEN-LAST:event_GraphButtonActionPerformed

    /** Кнопка для генерації значень */
    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
        view.viewInit(); view.viewShow();
        graph.updateGraph(view);
        ResultLabel.setText("Generation complete");
        subject.notifyObservers(view);
    }//GEN-LAST:event_GenerateButtonActionPerformed

    /** Кнопка для збереження значень до файлу */
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        System.out.println("Save current.");
        try { view.viewSave(); ResultLabel.setText("Save complete");
        } catch (IOException e) { System.err.println("Serialization error: " + e); ResultLabel.setText("Serialization error"); }
        view.viewShow();
        subject.notifyObservers(view);
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**  Кнопка для відновлення збережених значень з файлу */
    private void RestoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreButtonActionPerformed
        System.out.println("Restore last saved");
        try { view.viewRestore(); ResultLabel.setText("Restore complete");
        } catch (Exception e) { System.err.println("Serialization error: " + e); ResultLabel.setText("Serialization error"); }
        view.viewShow();
        subject.notifyObservers(view);
    }//GEN-LAST:event_RestoreButtonActionPerformed

    /**  @param args the command line arguments */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeButton;
    private javax.swing.JButton GenerateButton;
    private javax.swing.JButton GraphButton;
    private javax.swing.JButton RestoreButton;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
